[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd packages/demo-app && npm install"]

[phases.build]
cmds = ["cd packages/demo-app && npx vite build"]

[start]
cmd = "cd packages/demo-app && npx serve dist -p $PORT -s"
